= gogs-ocp

== Requirements

This role is designed to set up Gogs (the Go Github Server) on an OpenShift cluster. The intended use for this role is in an Operator. The role does not set up Kubernetes controllers (like Deployments or ReplicaSets) but creates the Gogs Pod directly - this is the preferred approach to be used by an Operator.

This role also requires a PostgreSQL Database to be running in the same OpenShift project as the Gogs Server. This database needs to be set up first.

== Role Variables

[cols="2,1,1,4",options="header"]
|====
|Variable Name|Default|Required|Description
|_gogs_namespace|gogs|Yes|Project Name to install Gogs into
|_gogs_name|gogs|Yes|Name of the Gogs service. Ensure this name is unique in your namespace/project
|_gogs_ssl|False|No|Set up HTTPS for the Gogs Route
|_gogs_postgresql_service_name|postgresql|Yes|Name of the PostgreSQL service to connect (should be listening on port 5432)
|_gogs_postgresql_database_name|postgresql|Yes|Name of Database to connect to
|_gogs_postgresql_user|postgresql|Yes|Database User Name
|_gogs_postgresql_password|postgresql|Yes|Database Password
|_gogs_volume_size|1Gi|No|Size of Persistent Volume to be created
|_gogs_memory_request|512Mi|No|Minimum Memory Requirement
|_gogs_memory_limit|512Mi|No|Maximum Memory Requirement
|_gogs_cpu_request|200m|No|Minimum CPU Requirement
|_gogs_cpu_limit|500m|No|Maximum CPU Requirement
|_gogs_wait_for_init|true|No|Wait for the database pod to be running and ready
|_gogs_image|docker.io/wkulhanek/gitea|Yes|Container image for Gogs
|_gogs_image_tag|latest|Yes|Tag for Gogs container image
|_gogs_state|present|No|`present` to install, `absent` to remove
|====

== Dependencies

* k8s module.
* Running PostgreSQL database listening on port 5432
* Working .kube/config configuration.
* The Project/Namespace must exist

== Example Playbook

[source,yaml]
----
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Set up PostgreSQL
    include_role:
      name: ./roles/postgresql-ocp
    vars:
      _postgresql_namespace: "gogs"
      _postgresql_name: "postgresql-gogs"
      _postgresql_database_name: "gogsdb"
      _postgresql_user: "gogsuser"
      _postgresql_password: "gogspassword"
      _postgresql_volume_size: "4Gi"

  - name: Set up Gogs
    include_role:
      name: ./roles/gogs-ocp
    vars:
      _gogs_namespace: "gogs"
      _gogs_name: "gogs"
      _gogs_ssl: "True|
      _gogs_volume_size: "4Gi"
      _gogs_postgresql_service_name: "postgresql-gogs"
      _gogs_postgresql_database_name: gogsdb
      _gogs_postgresql_user: gogsuser
      _gogs_postgresql_password: gogspassword
----

== License

BSD
